name: build
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  test:
    uses: greboid/.github/.github/workflows/checkout-and-test-go.yml@master
    secrets: inherit
  auth_container:
    uses: greboid/.github/.github/workflows/checkout-build-and-push-docker.yml@master
    with:
      dockerfile: 'cmd/auth/Dockerfile'
      image: 'registryauth/auth'
    secrets: inherit
    needs: [ test ]
  reg_container:
    uses: greboid/.github/.github/workflows/checkout-build-and-push-docker.yml@master
    with:
      dockerfile: 'cmd/authedreg/Dockerfile'
      image: 'registryauth/authedreg'
    secrets: inherit
    needs: [ test ]
  genpass_container:
    uses: greboid/.github/.github/workflows/checkout-build-and-push-docker.yml@master
    with:
      dockerfile: 'cmd/genpass/Dockerfile'
      image: 'registryauth/genpass'
    secrets: inherit
    needs: [ test ]
